#!/bin/bash
echo "Elevating permissions to root"
sudo echo "Permissions elevated to root"
sudo apt-get update
sudo apt-get install redis-server build-essential openssl libssl-dev curl libtool git tmux mongodb libkrb5-dev python curl -y;
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install --yes nodejs
sudo ln -s /usr/bin/nodejs /usr/bin/node
service mongodb start
service redis-server start
mongo < mongoSetup.txt
rm mongoSetup.txt
./setup
